<?
$map = array(
array(array('field' => 1,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 1,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0)),
array(array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0),array('field' => 0,'build'=>0))
);

//echo "<pre>";
//print_r($map);
echo base64_encode(gzcompress(serialize($map),9));